name: pizz_lecious
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_auth:
  firebase_core:
  flutter_bloc: ^8.1.6
  cloud_firestore: ^5.6.0
  curved_navigation_bar: ^1.0.6
  font_awesome_flutter: ^10.8.0
  logger:
  shared_preferences:
  flutter_credit_card:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
