// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSHitL-WuTpUHrTYxPCdVABBfoKsYH_Mo',
    appId: '1:202325109022:web:eb36c8ddeeee3f30ae410f',
    messagingSenderId: '202325109022',
    projectId: 'actual-pizzlicious',
    authDomain: 'actual-pizzlicious.firebaseapp.com',
    storageBucket: 'actual-pizzlicious.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE_9gPZzj-tMewht2qPVMcww2GS273xow',
    appId: '1:202325109022:android:972357a830048743ae410f',
    messagingSenderId: '202325109022',
    projectId: 'actual-pizzlicious',
    storageBucket: 'actual-pizzlicious.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbn-cosIgnDxceZErVucNNDFINDxg7xEg',
    appId: '1:202325109022:ios:c12d0f0bbbc25629ae410f',
    messagingSenderId: '202325109022',
    projectId: 'actual-pizzlicious',
    storageBucket: 'actual-pizzlicious.firebasestorage.app',
    iosBundleId: 'com.example.pizzLecious',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbn-cosIgnDxceZErVucNNDFINDxg7xEg',
    appId: '1:202325109022:ios:c12d0f0bbbc25629ae410f',
    messagingSenderId: '202325109022',
    projectId: 'actual-pizzlicious',
    storageBucket: 'actual-pizzlicious.firebasestorage.app',
    iosBundleId: 'com.example.pizzLecious',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSHitL-WuTpUHrTYxPCdVABBfoKsYH_Mo',
    appId: '1:202325109022:web:337cd2ca34170ef5ae410f',
    messagingSenderId: '202325109022',
    projectId: 'actual-pizzlicious',
    authDomain: 'actual-pizzlicious.firebaseapp.com',
    storageBucket: 'actual-pizzlicious.firebasestorage.app',
  );
}
